name: Daily Form Submission

# Runs daily at random times between 6:00-6:05 PM IST (12:30-12:35 UTC)
# Multiple schedules provide randomization since GitHub Actions doesn't support random timing
on:
  schedule:
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '31 12 * * *'  # 6:01 PM IST  
    - cron: '32 12 * * *'  # 6:02 PM IST
    - cron: '33 12 * * *'  # 6:03 PM IST
    - cron: '34 12 * * *'  # 6:04 PM IST
    - cron: '35 12 * * *'  # 6:05 PM IST
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  submit-form:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install ChromeDriver using the new JSON API
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
        echo "Chrome major version: $CHROME_VERSION"
        
        # Get the latest ChromeDriver version for this Chrome major version
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # Download and install ChromeDriver
        wget -N "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" -P ~/
        unzip ~/chromedriver-linux64.zip -d ~/
        sudo mv ~/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Verify installation
        chromedriver --version
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check if already submitted today
      id: check_submission
      run: |
        TODAY=$(date -u +"%Y-%m-%d")
        echo "today=$TODAY" >> $GITHUB_OUTPUT
        echo "Checking for today's submission: $TODAY"
        
    - name: Submit Google Form (Selenium)
      run: python submit_form_selenium.py
      
    - name: Submit Google Form (Requests fallback)
      if: failure()
      run: |
        echo "Selenium method failed, trying requests method..."
        python submit_form.py
      continue-on-error: true
      
    - name: Log completion  
      run: echo "Daily form submission workflow completed at $(date -u)"